lab02/encuesta/urls.py
from django.urls import path
from . import views

app_name = 'encuesta'

urlpatterns = [
    # ex: /encuesta/
    path('', views.index, name = 'index'),
    path('enviar', views.enviar, name = 'enviar'),
    path('calculo/', views.calculo, name='calculo'),
    path('calculo/resultado/', views.calculo_resultado, name='calculo_resultado'),
    path('cilindro/', views.cilindro, name='cilindro'),
    path('cilindro/resultado/', views.cilindro_resultado, name='cilindro_resultado'),
]

lab02/lab02/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('encuesta/', include('encuesta.urls')),
    path('admin/', admin.site.urls),
]

lab02/encuesta/models.py
from django.db import models

# Create your models here.

lab02/encuesta/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context = {
        'titulo' : "Formulario",
    }
    return render(request, 'encuesta/formulario.html', context)

def enviar(request):
    context = {
        'titulo' : "Respuesta",
        'nombre' : request.POST['nombre'],
        'clave' : request.POST['password'],
        'educacion' : request.POST['educacion'],
        'nacionalidad' : request.POST['nacionalidad'],
        'idiomas' : request.POST.getlist('idiomas'),
        'correo' : request.POST['email'],
        'website' : request.POST['sitioweb'],
    }
    return render(request, 'encuesta/respuesta.html', context)


# Formulario de operaciones basicas
def calculo(request):
    return render(request, 'encuesta/calculo.html')

def calculo_resultado(request):
    # Aquí realizarás la operación y mostrar resultado
    num1 = float(request.POST['num1'])
    num2 = float(request.POST['num2'])
    operacion = request.POST['operacion']

    if operacion == 'suma':
        resultado = num1 + num2
    elif operacion == 'resta':
        resultado = num1 - num2
    elif operacion == 'multiplicacion':
        resultado = num1 * num2
    else:
        resultado = None

    context = {
        'num1': num1,
        'num2': num2,
        'operacion': operacion,
        'resultado': resultado,
    }
    return render(request, 'encuesta/calculo_resultado.html', context)


# Formulario del volumen de un ciclindro
def cilindro(request):
    return render(request, 'encuesta/cilindro.html')

def cilindro_resultado(request):
    # Aquí realizará el cálculo del volumen
    altura = float(request.POST['altura'])
    diametro = float(request.POST['diametro'])

    # Calcula el radio a partir del diámetro
    radio = diametro / 2

    # Calcula el volumen del cilindro
    volumen = 3.14159265358979323846 * (radio ** 2) * altura

    context = {
        'altura': altura,
        'diametro': diametro,
        'volumen': volumen,
    }
    return render(request, 'encuesta/cilindro_resultado.html', context)

lab02/encuesta/templates/encuesta/calculo.html
<h2>Calculadora</h2>
<form action="{% url 'encuesta:calculo_resultado' %}" method="post">
    {% csrf_token %}
    Primer número:
    <input type="number" name="num1"><br> <br>
    Segundo número:
    <input type="number" name="num2"><br> <br>
    Operación:
    <select name="operacion">
        <option value="suma">Suma</option>
        <option value="resta">Resta</option>
        <option value="multiplicacion">Multiplicación</option>
    </select><br> <br>
    <input type="submit" value="Calcular">
</form>

lab02/encuesta/templates/encuesta/calculo_resultado.html
<h2>Resultado</h2>
{% if resultado is not None %}
La {{ operacion }} de {{ num1 }} y {{ num2 }} es igual a {{ resultado }}.
{% else %}
Operación no válida.
{% endif %}
<br>
<a href="{% url 'encuesta:calculo' %}">Volver al formulario</a>

lab02/encuesta/templates/encuesta/cilindro.html
<h2>Calculadora de Cilindro</h2>
<form action="{% url 'encuesta:cilindro_resultado' %}" method="post">
    {% csrf_token %}
    Altura (metros):
    <input type="number" name="altura" step="0.01"><br> <br>
    Diámetro (metros):
    <input type="number" name="diametro" step="0.01"><br> <br>
    <input type="submit" value="Calcular Volumen">
</form>

lab02/encuesta/templates/encuesta/cilindro_resultado.html
<h2>Resultado del Cálculo</h2>
{% if volumen is not None %}
El volumen del cilindro calculado es {{ volumen }} metros cúbicos.
{% else %}
Los datos ingresados no son válidos.
{% endif %}
<br>
<a href="{% url 'encuesta:cilindro' %}">Volver al formulario</a>

lab02/encuesta/templates/encuesta/formulario.html
<h2>{{ titulo }}</h2>
<form action="{% url 'encuesta:enviar' %}" method="post">
    {% csrf_token %}
    Nombre:
    <input type="text" name="nombre" maxlength="50"><br>
    Contraseña:
    <input type="password" name="password"><br>
    Educacion:
    <select name="educacion">
        <option value="sin-estudios">Sin estudios</option>
        <option value="educacion-obligatoria" selected="selected">Educacion obligatoria</option>
        <option value="formacion-profesional">Formacion profesional</option>
        <option value="universidad">Universidad</option>
    </select><br>
    Nacionalidad:
    <input type="radio" name="nacionalidad" value="hispana">Hispana</input>
    <input type="radio" name="nacionalidad" value="otra">Otra</input><br>
    Idiomas:
    <input type="checkbox" name="idiomas" value="español" checked="checked">Español</input>
    <input type="checkbox" name="idiomas" value="ingles">Ingles</input>
    <input type="checkbox" name="idiomas" value="frances">Frances</input>
    <input type="checkbox" name="idiomas" value="Aleman">Aleman</input> <br>
    Email:
    <input type="text" name="email"><br>
    Sitio Web:
    <input type="text" name="sitioweb"><br>
    // Boton de enviar
    <input type="submit" name="submit" value="enviar">
</form> <br>
<a href="{% url 'encuesta:calculo' %}">Calcular</a> <br>
<a href="{% url 'encuesta:cilindro' %}">Calcular Volumen del Cilindro</a>

lab02/encuesta/templates/encuesta/respuesta.html
<h2>{{ titulo }}</h2>
<p>Nombre: {{ nombre }}</p>
<p>Clave: {{ clave }}</p>
<p>Educacion: {{ educacion }}</p>
<p>Nacionalidad: {{ nacionalidad }}</p>
<p>Idiomas:</p>
<ul>
    {% for item in idiomas %}
    <li>{{ item }}</li>
    {% endfor %}
</ul>
<p>Email: {{ correo }}</p>
<p>Sitio Web: {{ website }}</p>